### ISSUE TITLE
Add attribution for map data

### ISSUE THREAD

**Issue by blackboxlogic** [sdl60660/river-runner#12]
It looks like the poi map data (not the imagery) is sourced from OSM, but you haven't provided attribution as required by OSM's license.

I viewed the page on a mobile browser.

For more information, please see https://www.openstreetmap.org/copyright

**Comment by sdl60660** [comment]
Ah, it's on there, but I think it's actually being blocked by the footer on mobile. I'll fix that!

**Comment by sdl60660** [comment]
Fixed on #15 (though mapbox, by default, collapses attribution into a little button you have to tap). The attribution was hidden under the mobile footer, but that's now fixed.
