### ISSUE TITLE
Spins forever on Ketchum, Idaho

### ISSUE THREAD

**Issue by wffurr** [sdl60660/river-runner#13]
If I click on the mountains in central Idaho, I sometimes get "can't find a flowpath" and sometimes it just spins forever (>30 minutes).

**Comment by sdl60660** [comment]
Yeah, this is connected to #11 I'll work on fixing this.

**Comment by sdl60660** [comment]
Fixed on #16

**Comment by wffurr** [comment]
Great, thanks Sam!
