### ISSUE TITLE
Transboundary rivers hang app

### ISSUE THREAD

**Issue by Chrismarsh** [sdl60660/river-runner#17]
I tried a trans-boundary basin ([Red River](https://www.ijc.org/en/watersheds/red-river) ) that flows north into Canada and it hung the app.

![image](https://user-images.githubusercontent.com/630436/120006013-b2755b80-bf95-11eb-8bb8-859fa4201c70.png)

**Comment by sdl60660** [comment]
Ah, cool, I'll fix this. Had heard of this error, but couldn't recreate it to check the issue, I'll use this to to test it.
