### ISSUE TITLE
Hebrew is backwards

### ISSUE THREAD

**Issue by diericx** [sdl60660/river-runner#25]
Might not be an issue on your end at all, but I noticed Israel appears like this:
לארשי
But it should be:
׳שראל

All Hebrew is reading left to right instead of right to left. I cannot confirm the issue affects other RTL languages, but I would assume so.

**Comment by sdl60660** [comment]
Ah, interesting. Were you seeing that in the navigation box in the top-right corner, or on the map? Or was this on mobile?

**Comment by diericx** [comment]
Desktop, on the map
Confirmed issue is on both Firefox 95.0.2 and Safari 15.1 on MacOS 12.0.1

**Comment by sdl60660** [comment]
Should be resolved now, on this commit: https://github.com/sdl60660/river-runner/commit/08e2f85a15c78efc638c032674cb766b9f1764fe

Thank you!
