### ISSUE TITLE
Endorheic Basins (Example: Lake Atitlán, Guatemala)

### ISSUE THREAD

**Issue by csantosumich** [sdl60660/river-runner#26]
Lake Atitlán is a very deep, very picturesque lake in the Guatemalan Highlands (think Lake Como, but ringed by several immense volcanoes), the result of a caldera explosion many years ago.  It does not drain into the Pacific Ocean (at least not directly).  

There are many such basins around the world (https://en.wikipedia.org/wiki/Endorheic_basin).  

The application should reflect these flows, if possible, so that a rain drop placed in the Atitlan basin, flows to the lake, and stops there.  It would be an incredible update to show the many people living around these lakes or swamps that their water doesn't actually go all that far.  Unfortunately, agricultural runoff in the Atitlan basin doesn't "disappear" (does it ever though?).  It just flows a few kilometers and builds up in the lake, threatening this unique ecosystem!  The same applies to other fragile ecosystems, including desert basins, swamps, etc.

Aside from that, excellent application for teaching!

**Comment by sdl60660** [comment]
Hello! As far as I can tell, the drainage into Lake Atitlan is represented correctly (e.g.  https://river-runner-global.samlearner.com/?lng=-91.17409591436403&lat=14.791363055793568), as are other endhoric basins. It seems it might be missing from the stop feature list and labeled incorrectly as the ocean, which I will correct.

**Comment by sdl60660** [comment]
Thank you!

**Comment by sdl60660** [comment]
Lake Atitlán should now be labeled correctly!
