### ISSUE TITLE
Difficult to visually track blue path

### ISSUE THREAD

**Issue by caretcaret** [sdl60660/river-runner#3]
It's sometimes hard to see the blue line while the rest of the screen is moving, and it'd be better if it had thicker line weight.

**Comment by sdl60660** [comment]
I'll bump the line width up a little when I merge this next branch. I started with it much thicker and at a certain point, it sort of distracts from the surrounding environment, but you're probably right that it's too thin right now.

**Comment by sdl60660** [comment]
Bumped it up one unit, but let me know if you think it's still hard to see it have other solutions. Could be a path smoothing thing too, since it'll lose some of the contours of the true path.
